export interface MedicationLibEntry {
  name: string;
  genericName: string;
  category: string;
  presentation: string;
  unit: string;
  controlled?: boolean;
}

export const RENAME_2024: MedicationLibEntry[] = [
  // Analgésicos e Antitérmicos
  { name: "DIPIRONA SÓDICA 500MG", genericName: "DIPIRONA SÓDICA", category: "analgesic", presentation: "Comprimido 500mg", unit: "cp", controlled: false },
  { name: "DIPIRONA SÓDICA 500MG/ML", genericName: "DIPIRONA SÓDICA", category: "analgesic", presentation: "Ampola 2ml", unit: "amp", controlled: false },
  { name: "PARACETAMOL 500MG", genericName: "PARACETAMOL", category: "analgesic", presentation: "Comprimido 500mg", unit: "cp", controlled: false },
  { name: "PARACETAMOL 200MG/ML", genericName: "PARACETAMOL", category: "analgesic", presentation: "Frasco gotas 15ml", unit: "fr", controlled: false },
  { name: "IBUPROFENO 600MG", genericName: "IBUPROFENO", category: "analgesic", presentation: "Comprimido 600mg", unit: "cp", controlled: false },
  { name: "IBUPROFENO 50MG/ML", genericName: "IBUPROFENO", category: "analgesic", presentation: "Frasco gotas 30ml", unit: "fr", controlled: false },
  { name: "CETOROLACO 10MG", genericName: "CETOROLACO DE TROMETAMINA", category: "analgesic", presentation: "Comprimido Sublingual 10mg", unit: "cp", controlled: false },
  { name: "TRAMADOL 50MG", genericName: "CLORIDRATO DE TRAMADOL", category: "narcotic", presentation: "Cápsula 50mg", unit: "cap", controlled: true },
  { name: "TRAMADOL 100MG/2ML", genericName: "CLORIDRATO DE TRAMADOL", category: "narcotic", presentation: "Ampola 2ml", unit: "amp", controlled: true },
  { name: "MORFINA 10MG/ML", genericName: "SULFATO DE MORFINA", category: "narcotic", presentation: "Ampola 1ml", unit: "amp", controlled: true },
  { name: "MORFINA 10MG", genericName: "SULFATO DE MORFINA", category: "narcotic", presentation: "Comprimido 10mg", unit: "cp", controlled: true },
  { name: "FENTANIL 0,05MG/ML 2ML", genericName: "CITRATO DE FENTANILA", category: "narcotic", presentation: "Ampola 2ml", unit: "amp", controlled: true },
  { name: "FENTANIL 0,05MG/ML 10ML", genericName: "CITRATO DE FENTANILA", category: "narcotic", presentation: "Ampola 10ml", unit: "amp", controlled: true },
  { name: "PETIDINA 50MG/ML 2ML", genericName: "CLORIDRATO DE PETIDINA", category: "narcotic", presentation: "Ampola 2ml", unit: "amp", controlled: true },
  { name: "CETAMINA 50MG/ML 2ML", genericName: "CLORIDRATO DE CETAMINA", category: "psychotropic", presentation: "Ampola 2ml", unit: "amp", controlled: true },
  { name: "CODEÍNA 30MG", genericName: "FOSFATO DE CODEÍNA", category: "narcotic", presentation: "Comprimido 30mg", unit: "cp", controlled: true },
  { name: "METADONA 10MG", genericName: "CLORIDRATO DE METADONA", category: "narcotic", presentation: "Comprimido 10mg", unit: "cp", controlled: true },
  { name: "OXICODONA 10MG", genericName: "CLORIDRATO DE OXICODONA", category: "narcotic", presentation: "Comprimido 10mg", unit: "cp", controlled: true },
  { name: "REMIFENTANILA 2MG", genericName: "CLORIDRATO DE REMIFENTANILA", category: "narcotic", presentation: "Frasco-ampola", unit: "fr", controlled: true },
  { name: "REMILFENTANILA 2MG (IV)", genericName: "CLORIDRATO DE REMIFENTANILA", category: "narcotic", presentation: "Frasco-ampola", unit: "fr", controlled: true },
  { name: "ALFENTANILA 0,5MG/ML 5ML", genericName: "CLORIDRATO DE ALFENTANILA", category: "narcotic", presentation: "Ampola 5ml", unit: "amp", controlled: true },
  { name: "HIDROMORFONA 2MG", genericName: "CLORIDRATO DE HIDROMORFONA", category: "narcotic", presentation: "Comprimido 2mg", unit: "cp", controlled: true },
  { name: "OXICODONA 20MG", genericName: "CLORIDRATO DE OXICODONA", category: "narcotic", presentation: "Comprimido 20mg", unit: "cp", controlled: true },

  // Anti-inflamatórios
  { name: "DICLOFENACO SÓDICO 50MG", genericName: "DICLOFENACO SÓDICO", category: "anti-inflammatory", presentation: "Comprimido 50mg", unit: "cp", controlled: false },
  { name: "DICLOFENACO SÓDICO 75MG/3ML", genericName: "DICLOFENACO SÓDICO", category: "anti-inflammatory", presentation: "Ampola 3ml", unit: "amp", controlled: false },
  { name: "CETOPROFENO 100MG", genericName: "CETOPROFENO", category: "anti-inflammatory", presentation: "Comprimido 100mg", unit: "cp", controlled: false },
  { name: "CETOPROFENO 100MG (IM)", genericName: "CETOPROFENO", category: "anti-inflammatory", presentation: "Frasco-ampola + diluente", unit: "fr", controlled: false },
  { name: "NIMESULIDA 100MG", genericName: "NIMESULIDA", category: "anti-inflammatory", presentation: "Comprimido 100mg", unit: "cp", controlled: false },

  // Antibióticos
  { name: "AMOXICILINA 500MG", genericName: "AMOXICILINA", category: "antibiotic", presentation: "Cápsula 500mg", unit: "cap", controlled: false },
  { name: "AMOXICILINA 250MG/5ML", genericName: "AMOXICILINA", category: "antibiotic", presentation: "Pó para suspensão 150ml", unit: "fr", controlled: false },
  { name: "AMOXICILINA + CLAVULANATO", genericName: "AMOXICILINA + CLAVULANATO DE POTÁSSIO", category: "antibiotic", presentation: "Comprimido 500mg + 125mg", unit: "cp", controlled: false },
  { name: "CEFTRIAXONA 1G (IM)", genericName: "CEFTRIAXONA SÓDICA", category: "antibiotic", presentation: "Frasco-ampola + diluente", unit: "fr", controlled: false },
  { name: "CEFTRIAXONA 1G (IV)", genericName: "CEFTRIAXONA SÓDICA", category: "antibiotic", presentation: "Frasco-ampola + diluente", unit: "fr", controlled: false },
  { name: "CEFALEXINA 500MG", genericName: "CEFALEXINA", category: "antibiotic", presentation: "Cápsula 500mg", unit: "cap", controlled: false },
  { name: "AZITROMICINA 500MG", genericName: "AZITROMICINA", category: "antibiotic", presentation: "Comprimido 500mg", unit: "cp", controlled: false },
  { name: "CIPROFLOXACINO 500MG", genericName: "CLORIDRATO DE CIPROFLOXACINO", category: "antibiotic", presentation: "Comprimido 500mg", unit: "cp", controlled: false },
  { name: "METRONIDAZOL 250MG", genericName: "METRONIDAZOL", category: "antibiotic", presentation: "Comprimido 250mg", unit: "cp", controlled: false },
  { name: "CLINDAMICINA 300MG", genericName: "CLORIDRATO DE CLINDAMICINA", category: "antibiotic", presentation: "Cápsula 300mg", unit: "cap", controlled: false },
  { name: "BENZILPENICILINA BENZATINA 1.200.000 UI", genericName: "BENZILPENICILINA BENZATINA", category: "antibiotic", presentation: "Frasco-ampola", unit: "fr", controlled: false },
  { name: "SULFAMETOXAZOL + TRIMETOPRIMA", genericName: "SULFAMETOXAZOL + TRIMETOPRIMA", category: "antibiotic", presentation: "Comprimido 400mg + 80mg", unit: "cp", controlled: false },
  { name: "DOXICICLINA 100MG", genericName: "CLORIDRATO DE DOXICICLINA", category: "antibiotic", presentation: "Comprimido 100mg", unit: "cp", controlled: false },
  { name: "LEVOFLOXACINO 500MG", genericName: "LEVOFLOXACINO", category: "antibiotic", presentation: "Comprimido 500mg", unit: "cp", controlled: false },
  { name: "NITROFURANTOÍNA 100MG", genericName: "NITROFURANTOÍNA", category: "antibiotic", presentation: "Cápsula 100mg", unit: "cap", controlled: false },
  { name: "RIFAMPICINA 300MG", genericName: "RIFAMPICINA", category: "antibiotic", presentation: "Cápsula 300mg", unit: "cap", controlled: false },
  { name: "ISONIAZIDA 100MG", genericName: "ISONIAZIDA", category: "antibiotic", presentation: "Comprimido 100mg", unit: "cp", controlled: false },
  { name: "PIRAZINAMIDA 500MG", genericName: "PIRAZINAMIDA", category: "antibiotic", presentation: "Comprimido 500mg", unit: "cp", controlled: false },
  { name: "ETAMBUTOL 400MG", genericName: "CLORIDRATO DE ETAMBUTOL", category: "antibiotic", presentation: "Comprimido 400mg", unit: "cp", controlled: false },
  { name: "ALBENDAZOL 400MG", genericName: "ALBENDAZOL", category: "antibiotic", presentation: "Comprimido Mastigável", unit: "cp", controlled: false },
  { name: "MEBENDAZOL 100MG", genericName: "MEBENDAZOL", category: "antibiotic", presentation: "Comprimido 100mg", unit: "cp", controlled: false },
  { name: "SULFADIAZINA 500MG", genericName: "SULFADIAZINA", category: "antibiotic", presentation: "Comprimido 500mg", unit: "cp", controlled: false },
  { name: "PIRIMETAMINA 25MG", genericName: "PIRIMETAMINA", category: "antibiotic", presentation: "Comprimido 25mg", unit: "cp", controlled: false },
  { name: "ESTREPTOMICINA 1G", genericName: "SULFATO DE ESTREPTOMICINA", category: "antibiotic", presentation: "Frasco-ampola", unit: "fr", controlled: false },
  { name: "ERITROMICINA 250MG/5ML", genericName: "ESTOLATO DE ERITROMICINA", category: "antibiotic", presentation: "Suspensão 100ml", unit: "fr", controlled: false },
  { name: "TETRACICLINA 500MG", genericName: "CLORIDRATO DE TETRACICLINA", category: "antibiotic", presentation: "Cápsula 500mg", unit: "cap", controlled: false },
  { name: "NORFLOXACINO 400MG", genericName: "NORFLOXACINO", category: "antibiotic", presentation: "Comprimido 400mg", unit: "cp", controlled: false },

  // Antialérgicos
  { name: "LORATADINA 10MG", genericName: "LORATADINA", category: "allergy", presentation: "Comprimido 10mg", unit: "cp", controlled: false },
  { name: "DEXCLORFENIRAMINA 0,4MG/ML", genericName: "MALEATO DE DEXCLORFENIRAMINA", category: "allergy", presentation: "Xarope 120ml", unit: "fr", controlled: false },
  { name: "PROMETAZINA 25MG", genericName: "CLORIDRATO DE PROMETAZINA", category: "allergy", presentation: "Comprimido 25mg", unit: "cp", controlled: false },
  { name: "PROMETAZINA 50MG/2ML", genericName: "CLORIDRATO DE PROMETAZINA", category: "allergy", presentation: "Ampola 2ml", unit: "amp", controlled: false },

  // Corticoides
  { name: "HIDROCORTISONA 100MG", genericName: "SUCCINATO SÓDICO DE HIDROCORTISONA", category: "corticoid", presentation: "Frasco-ampola", unit: "fr", controlled: false },
  { name: "HIDROCORTISONA 500MG", genericName: "SUCCINATO SÓDICO DE HIDROCORTISONA", category: "corticoid", presentation: "Frasco-ampola", unit: "fr", controlled: false },
  { name: "DEXAMETASONA 4MG", genericName: "DEXAMETASONA", category: "corticoid", presentation: "Comprimido 4mg", unit: "cp", controlled: false },
  { name: "DEXAMETASONA 4MG/ML", genericName: "FOSFATO DISSODICO DE DEXAMETASONA", category: "corticoid", presentation: "Ampola 2,5ml", unit: "fr", controlled: false },
  { name: "PREDNISONA 20MG", genericName: "PREDNISONA", category: "corticoid", presentation: "Comprimido 20mg", unit: "cp", controlled: false },
  { name: "PREDNISONA 5MG", genericName: "PREDNISONA", category: "corticoid", presentation: "Comprimido 5mg", unit: "cp", controlled: false },
  { name: "METILPREDNISOLONA 125MG", genericName: "SUCCINATO SÓDICO DE METILPREDNISOLONA", category: "corticoid", presentation: "Frasco-ampola 125mg", unit: "fr", controlled: false },
  { name: "PREDNISOLONA 3MG/ML", genericName: "FOSFATO SÓDICO DE PREDNISOLONA", category: "corticoid", presentation: "Solução oral 60ml", unit: "fr", controlled: false },

  // Cardiovasculares
  { name: "CAPTOPRIL 25MG", genericName: "CAPTOPRIL", category: "cardiovascular", presentation: "Comprimido 25mg", unit: "cp", controlled: false },
  { name: "ENALAPRIL 10MG", genericName: "MALEATO DE ENALAPRIL", category: "cardiovascular", presentation: "Comprimido 10mg", unit: "cp", controlled: false },
  { name: "LOSARTANA POTÁSSICA 50MG", genericName: "LOSARTANA POTÁSSICA", category: "cardiovascular", presentation: "Comprimido 50mg", unit: "cp", controlled: false },
  { name: "ATENOLOL 50MG", genericName: "ATENOLOL", category: "cardiovascular", presentation: "Comprimido 50mg", unit: "cp", controlled: false },
  { name: "ATENOLOL 25MG", genericName: "ATENOLOL", category: "cardiovascular", presentation: "Comprimido 25mg", unit: "cp", controlled: false },
  { name: "PROPRANOLOL 40MG", genericName: "CLORIDRATO DE PROPRANOLOL", category: "cardiovascular", presentation: "Comprimido 40mg", unit: "cp", controlled: false },
  { name: "FUROSEMIDA 40MG", genericName: "FUROSEMIDA", category: "cardiovascular", presentation: "Comprimido 40mg", unit: "cp", controlled: false },
  { name: "FUROSEMIDA 20MG/2ML", genericName: "FUROSEMIDA", category: "cardiovascular", presentation: "Ampola 2ml", unit: "amp", controlled: false },
  { name: "HIDRALAZINA 25MG", genericName: "CLORIDRATO DE HIDRALAZINA", category: "cardiovascular", presentation: "Comprimido 25mg", unit: "cp", controlled: false },
  { name: "ESPIRONOLACTONA 25MG", genericName: "ESPIRONOLACTONA", category: "cardiovascular", presentation: "Comprimido 25mg", unit: "cp", controlled: false },
  { name: "HIDROCLOROTIAZIDA 25MG", genericName: "HIDROCLOROTIAZIDA", category: "cardiovascular", presentation: "Comprimido 25mg", unit: "cp", controlled: false },
  { name: "METILDOPA 250MG", genericName: "METILDOPA", category: "cardiovascular", presentation: "Comprimido 250mg", unit: "cp", controlled: false },
  { name: "DIGOXINA 0,25MG", genericName: "DIGOXINA", category: "cardiovascular", presentation: "Comprimido 0,25mg", unit: "cp", controlled: false },
  { name: "MONONITRATO DE ISOSSORBIDA 20MG", genericName: "MONONITRATO DE ISOSSORBIDA", category: "cardiovascular", presentation: "Comprimido 20mg", unit: "cp", controlled: false },
  { name: "ANLODIPINO 5MG", genericName: "BESILATO DE ANLODIPINO", category: "cardiovascular", presentation: "Comprimido 5mg", unit: "cp", controlled: false },
  { name: "ANLODIPINO 10MG", genericName: "BESILATO DE ANLODIPINO", category: "cardiovascular", presentation: "Comprimido 10mg", unit: "cp", controlled: false },
  { name: "CARVEDILOL 6,25MG", genericName: "CARVEDILOL", category: "cardiovascular", presentation: "Comprimido 6,25mg", unit: "cp", controlled: false },
  { name: "CARVEDILOL 12,5MG", genericName: "CARVEDILOL", category: "cardiovascular", presentation: "Comprimido 12,5mg", unit: "cp", controlled: false },
  { name: "CARVEDILOL 25MG", genericName: "CARVEDILOL", category: "cardiovascular", presentation: "Comprimido 25mg", unit: "cp", controlled: false },
  { name: "CLOPIDOGREL 75MG", genericName: "BISSULFATO DE CLOPIDOGREL", category: "cardiovascular", presentation: "Comprimido 75mg", unit: "cp", controlled: false },
  { name: "DILTIAZEM 60MG", genericName: "CLORIDRATO DE DILTIAZEM", category: "cardiovascular", presentation: "Comprimido 60mg", unit: "cp", controlled: false },
  { name: "NIFEDIPINA 20MG (RETARD)", genericName: "NIFEDIPINA", category: "cardiovascular", presentation: "Comprimido 20mg", unit: "cp", controlled: false },
  { name: "VERAPAMIL 80MG", genericName: "CLORIDRATO DE VERAPAMIL", category: "cardiovascular", presentation: "Comprimido 80mg", unit: "cp", controlled: false },

  // Emergência e Reanimação
  { name: "ADRENALINA 1MG/ML", genericName: "EPINEFRINA", category: "emergency", presentation: "Ampola 1ml", unit: "amp", controlled: false },
  { name: "ATROPINA 0,25MG/ML", genericName: "SULFATO DE ATROPINA", category: "emergency", presentation: "Ampola 1ml", unit: "amp", controlled: false },
  { name: "AMIODARONA 150MG/3ML", genericName: "CLORIDRATO DE AMIODARONA", category: "emergency", presentation: "Ampola 3ml", unit: "amp", controlled: false },
  { name: "LIDOCAÍNA 2% S/VASO", genericName: "CLORIDRATO DE LIDOCAÍNA", category: "emergency", presentation: "Frasco 20ml", unit: "fr", controlled: false },
  { name: "NITROPRUSSIATO 50MG", genericName: "NITROPRUSSIATO DE SÓDIO", category: "high-alert", presentation: "Frasco-ampola + diluente", unit: "fr", controlled: false },
  { name: "DOPAMINA 5MG/ML", genericName: "CLORIDRATO DE DOPAMINA", category: "high-alert", presentation: "Ampola 10ml", unit: "amp", controlled: false },
  { name: "NORADRENALINA 1MG/ML", genericName: "HEMITARTARATO DE NOREPINEFRINA", category: "high-alert", presentation: "Ampola 4ml", unit: "amp", controlled: false },
  { name: "HEPARINA 5.000 UI/ML 5ML", genericName: "HEPARINA SÓDICA", category: "high-alert", presentation: "Frasco-ampola 5ml", unit: "fr", controlled: false },
  { name: "ENOXAPARINA 40MG/0,4ML", genericName: "ENOXAPARINA SÓDICA", category: "high-alert", presentation: "Seringa preenchida", unit: "un", controlled: false },
  { name: "WARFARINA 5MG", genericName: "VARFARINA SÓDICA", category: "high-alert", presentation: "Comprimido 5mg", unit: "cp", controlled: false },
  { name: "CLORETO DE POTÁSSIO 19,1% 10ML", genericName: "CLORETO DE POTÁSSIO 19,1%", category: "high-alert", presentation: "Ampola 10ml", unit: "amp", controlled: false },
  { name: "SULFATO DE MAGNÉSIO 50% 10ML", genericName: "SULFATO DE MAGNÉSIO 50%", category: "high-alert", presentation: "Ampola 10ml", unit: "amp", controlled: false },
  { name: "FOSFATO DE POTÁSSIO 2MEQ/ML", genericName: "FOSFATO DE POTÁSSIO", category: "high-alert", presentation: "Ampola 10ml", unit: "amp", controlled: false },
  { name: "GLUCONATO DE CÁLCIO 10% 10ML", genericName: "GLUCONATO DE CÁLCIO 10%", category: "high-alert", presentation: "Ampola 10ml", unit: "amp", controlled: false },
  { name: "BICARBONATO DE SÓDIO 8,4%", genericName: "BICARBONATO DE SÓDIO", category: "emergency", presentation: "Ampola 10ml", unit: "amp", controlled: false },
  { name: "GLUCONATO DE CÁLCIO 10%", genericName: "GLUCONATO DE CÁLCIO", category: "emergency", presentation: "Ampola 10ml", unit: "amp", controlled: false },
  { name: "SULFATO DE MAGNÉSIO 50%", genericName: "SULFATO DE MAGNÉSIO", category: "emergency", presentation: "Ampola 10ml", unit: "amp", controlled: false },

  // Endócrinos / Termolábeis
  { name: "INSULINA REGULAR", genericName: "INSULINA HUMANA REGULAR", category: "thermolabile", presentation: "Frasco 10ml (100UI/ml)", unit: "fr", controlled: false },
  { name: "INSULINA NPH", genericName: "INSULINA HUMANA NPH", category: "thermolabile", presentation: "Frasco 10ml (100UI/ml)", unit: "fr", controlled: false },
  { name: "OCITOCINA 5UI/ML (REFRIG)", genericName: "OCITOCINA", category: "thermolabile", presentation: "Ampola 1ml", unit: "amp", controlled: false },
  { name: "VACINA CONTRA HEPATITE B", genericName: "VACINA HEPATITE B", category: "thermolabile", presentation: "Frasco 0,5ml", unit: "fr", controlled: false },
  { name: "VACINA CONTRA INFLUENZA", genericName: "VACINA INFLUENZA", category: "thermolabile", presentation: "Frasco monodose", unit: "fr", controlled: false },
  { name: "SORO ANTIESCORPIÔNICO", genericName: "SORO ANTIESCORPIÔNICO", category: "thermolabile", presentation: "Ampola 5ml", unit: "amp", controlled: false },
  { name: "SORO ANTIOFÍDICO POLIVALENTE", genericName: "SORO ANTIOFÍDICO", category: "thermolabile", presentation: "Ampola 10ml", unit: "amp", controlled: false },
  { name: "VACINA TRÍPLICE VIRAL", genericName: "VACINA SCR", category: "thermolabile", presentation: "Frasco monodose", unit: "fr", controlled: false },
  { name: "ALVEOFACT 108MG", genericName: "SURFACTANTE PULMONAR", category: "thermolabile", presentation: "Frasco-ampola", unit: "fr", controlled: false },
  { name: "FATOR VIII RECOMBINANTE", genericName: "FATOR VIII", category: "thermolabile", presentation: "Frasco-ampola", unit: "fr", controlled: false },
  { name: "ERITROPOETINA 4.000 UI", genericName: "ERITROPOETINA HUMANA RECOMBINANTE", category: "thermolabile", presentation: "Frasco-ampola", unit: "fr", controlled: false },
  { name: "INTERFERON ALFA 2B", genericName: "INTERFERON ALFA 2B", category: "thermolabile", presentation: "Frasco-ampola", unit: "fr", controlled: false },
  { name: "VACINA BCG", genericName: "VACINA BCG", category: "thermolabile", presentation: "Frasco multidose", unit: "fr", controlled: false },
  { name: "VACINA TETRAVALENTE", genericName: "VACINA DTP+HIB", category: "thermolabile", presentation: "Frasco monodose", unit: "fr", controlled: false },
  { name: "IMUNOGLOBULINA ANTI-RH", genericName: "IMUNOGLOBULINA ANTI-D", category: "thermolabile", presentation: "Frasco-ampola", unit: "fr", controlled: false },
  { name: "GLIBENCLAMIDA 5MG", genericName: "GLIBENCLAMIDA", category: "endocrine", presentation: "Comprimido 5mg", unit: "cp", controlled: false },
  { name: "METFORMINA 500MG", genericName: "CLORIDRATO DE METFORMINA", category: "endocrine", presentation: "Comprimido 500mg", unit: "cp", controlled: false },
  { name: "METFORMINA 850MG", genericName: "CLORIDRATO DE METFORMINA", category: "endocrine", presentation: "Comprimido 850mg", unit: "cp", controlled: false },
  { name: "LEVOTIROXINA 25MCG", genericName: "LEVOTIROXINA SÓDICA", category: "endocrine", presentation: "Comprimido 25mcg", unit: "cp", controlled: false },
  { name: "LEVOTIROXINA 50MCG", genericName: "LEVOTIROXINA SÓDICA", category: "endocrine", presentation: "Comprimido 50mcg", unit: "cp", controlled: false },
  { name: "LIOTIRONINA 25MCG", genericName: "LIOTIRONINA SÓDICA", category: "endocrine", presentation: "Comprimido 25mcg", unit: "cp", controlled: false },
  { name: "GLIKLAZIDA 30MG (LIB. PROL.)", genericName: "GLICLAZIDA", category: "endocrine", presentation: "Comprimido 30mg", unit: "cp", controlled: false },
  { name: "GLIKLAZIDA 60MG (LIB. PROL.)", genericName: "GLICLAZIDA", category: "endocrine", presentation: "Comprimido 60mg", unit: "cp", controlled: false },
  { name: "GLIMEPIRIDA 2MG", genericName: "GLIMEPIRIDA", category: "endocrine", presentation: "Comprimido 2mg", unit: "cp", controlled: false },
  { name: "GLIMEPIRIDA 4MG", genericName: "GLIMEPIRIDA", category: "endocrine", presentation: "Comprimido 4mg", unit: "cp", controlled: false },
  { name: "INSULINA GLARGINA 100UI/ML", genericName: "INSULINA GLARGINA", category: "thermolabile", presentation: "Frasco 10ml", unit: "fr", controlled: false },

  // Gastrointestinais
  { name: "OMEPRAZOL 20MG", genericName: "OMEPRAZOL", category: "gastrointestinal", presentation: "Cápsula 20mg", unit: "cap", controlled: false },
  { name: "OMEPRAZOL 40MG (IV)", genericName: "OMEPRAZOL SÓDICO", category: "gastrointestinal", presentation: "Frasco-ampola + diluente", unit: "fr", controlled: false },
  { name: "ONDANSETRONA 4MG", genericName: "CLORIDRATO DE ONDANSETRONA", category: "gastrointestinal", presentation: "Comprimido 4mg", unit: "cp", controlled: false },
  { name: "ONDANSETRONA 8MG/4ML", genericName: "CLORIDRATO DE ONDANSETRONA", category: "gastrointestinal", presentation: "Ampola 4ml", unit: "amp", controlled: false },
  { name: "METOCLOPRAMIDA 10MG", genericName: "CLORIDRATO DE METOCLOPRAMIDA", category: "gastrointestinal", presentation: "Comprimido 10mg", unit: "cp", controlled: false },
  { name: "METOCLOPRAMIDA 10MG/2ML", genericName: "CLORIDRATO DE METOCLOPRAMIDA", category: "gastrointestinal", presentation: "Ampola 2ml", unit: "amp", controlled: false },
  { name: "DIMENIDRINATO + B6", genericName: "DIMENIDRINATO + PIRIDOXINA", category: "gastrointestinal", presentation: "Comprimido", unit: "cp", controlled: false },
  { name: "DIMENIDRINATO + B6 (INJ)", genericName: "DIMENIDRINATO + PIRIDOXINA", category: "gastrointestinal", presentation: "Ampola 1ml", unit: "amp", controlled: false },
  { name: "ESCOPOLAMINA 10MG", genericName: "BUTILBROMETO DE ESCOPOLAMINA", category: "gastrointestinal", presentation: "Comprimido 10mg", unit: "cp", controlled: false },
  { name: "ESCOPOLAMINA 20MG/ML", genericName: "BUTILBROMETO DE ESCOPOLAMINA", category: "gastrointestinal", presentation: "Ampola 1ml", unit: "amp", controlled: false },
  { name: "ESCOPOLAMINA + DIPIRONA", genericName: "BUTILBROMETO DE ESCOPOLAMINA + DIPIRONA", category: "gastrointestinal", presentation: "Ampola 5ml", unit: "amp", controlled: false },
  { name: "DOMPERIDONA 1MG/ML", genericName: "DOMPERIDONA", category: "gastrointestinal", presentation: "Suspensão oral 100ml", unit: "fr", controlled: false },
  { name: "SIMETICONA 75MG/ML", genericName: "SIMETICONA", category: "gastrointestinal", presentation: "Frasco gotas 15ml", unit: "fr", controlled: false },

  // Respiratórios
  { name: "SALBUTAMOL 100MCG", genericName: "SULFATO DE SALBUTAMOL", category: "respiratory", presentation: "Aerossol 100mcg/dose", unit: "fr", controlled: false },
  { name: "FENOTEROL 5MG/ML", genericName: "BROMIDRATO DE FENOTEROL", category: "respiratory", presentation: "Frasco gotas 20ml", unit: "fr", controlled: false },
  { name: "IPRATRÓPIO 0,25MG/ML", genericName: "BROMETO DE IPRATRÓPIO", category: "respiratory", presentation: "Frasco gotas 20ml", unit: "fr", controlled: false },
  { name: "AMINOFILINA 240MG/10ML", genericName: "AMINOFILINA", category: "respiratory", presentation: "Ampola 10ml", unit: "amp", controlled: false },

  // Geral / Rotina
  { name: "ÁCIDO ASCÓRBICO 500MG", genericName: "VITAMINA C", category: "general", presentation: "Comprimido 500mg", unit: "cp", controlled: false },
  { name: "ÁCIDO FÓLICO 5MG", genericName: "ÁCIDO FÓLICO", category: "general", presentation: "Comprimido 5mg", unit: "cp", controlled: false },
  { name: "SULFATO FERROSO 40MG", genericName: "SULFATO FERROSO", category: "general", presentation: "Comprimido 40mg", unit: "cp", controlled: false },
  { name: "COMPLEXO B DRÁGEAS", genericName: "VITAMINAS B", category: "general", presentation: "Drágea", unit: "cp", controlled: false },
  { name: "COMPLEXO B (INJ)", genericName: "VITAMINAS B", category: "general", presentation: "Ampola 2ml", unit: "amp", controlled: false },
  { name: "VITAMINA K1 10MG/ML", genericName: "FITOMENADIONA", category: "general", presentation: "Ampola 1ml", unit: "amp", controlled: false },
  { name: "HIDRÓXIDO DE ALUMÍNIO 6% 150ML", genericName: "HIDRÓXIDO DE ALUMÍNIO", category: "general", presentation: "Frasco suspensão", unit: "fr", controlled: false },
  { name: "MULTIVITAMÍNICO POLIVIT", genericName: "POLIVITAMÍNICO", category: "general", presentation: "Cápsula", unit: "cap", controlled: false },
  { name: "CARBONATO DE CÁLCIO 500MG", genericName: "CARBONATO DE CÁLCIO", category: "general", presentation: "Comprimido 500mg", unit: "cp", controlled: false },
  { name: "COLECALCIFEROL 7.000 UI", genericName: "VITAMINA D3", category: "general", presentation: "Cápsula", unit: "cap", controlled: false },
  { name: "TIAMINA 100MG", genericName: "VITAMINA B1", category: "general", presentation: "Comprimido 100mg", unit: "cp", controlled: false },
  { name: "PIRIDOXINA 40MG", genericName: "VITAMINA B6", category: "general", presentation: "Comprimido 40mg", unit: "cp", controlled: false },
  { name: "CIANOCOBALAMINA 5000MCG", genericName: "VITAMINA B12", category: "general", presentation: "Ampola 2ml", unit: "amp", controlled: false },
  { name: "ÁCIDO ACETILSALICÍLICO 100MG", genericName: "AAS", category: "general", presentation: "Comprimido 100mg", unit: "cp", controlled: false },
  { name: "SINVASTATINA 20MG", genericName: "SINVASTATINA", category: "general", presentation: "Comprimido 20mg", unit: "cp", controlled: false },

  // Quimioterapia (Exemplos p/ Teste de Cor)
  { name: "METOTREXATO 2,5MG", genericName: "METOTREXATO", category: "chemotherapy", presentation: "Comprimido 2,5mg", unit: "cp", controlled: false },
  { name: "CICLOFOSFAMIDA 50MG", genericName: "CICLOFOSFAMIDA", category: "chemotherapy", presentation: "Comprimido 50mg", unit: "cp", controlled: false },
  { name: "TAMOXIFENO 20MG", genericName: "CITRATO DE TAMOXIFENO", category: "chemotherapy", presentation: "Comprimido 20mg", unit: "cp", controlled: false },

  // Não Padronizado (Exemplos p/ Teste de Cor)
  { name: "MEDICAMENTO X (DEMANDA JUDICIAL)", genericName: "ESPECÍFICO", category: "non-standard", presentation: "Caixa", unit: "un", controlled: false },
  { name: "FORMULA ESPECIAL NUTRIÇÃO", genericName: "NUTRIÇÃO COMPLETA", category: "non-standard", presentation: "Lata 400g", unit: "un", controlled: false },

  { name: "DIAZEPAM 10MG", genericName: "DIAZEPAM", category: "psychotropic", presentation: "Comprimido 10mg", unit: "cp", controlled: true },
  { name: "DIAZEPAM 10MG/2ML", genericName: "DIAZEPAM", category: "psychotropic", presentation: "Ampola 2ml", unit: "amp", controlled: true },
  { name: "MIDAZOLAM 15MG", genericName: "MALEATO DE MIDAZOLAM", category: "psychotropic", presentation: "Comprimido 15mg", unit: "cp", controlled: true },
  { name: "MIDAZOLAM 5MG/ML", genericName: "CLORIDRATO DE MIDAZOLAM", category: "psychotropic", presentation: "Ampola 3ml", unit: "amp", controlled: true },
  { name: "FENITOÍNA 100MG", genericName: "FENITOÍNA SÓDICA", category: "psychotropic", presentation: "Comprimido 100mg", unit: "cp", controlled: false },
  { name: "FENITOÍNA 250MG/5ML", genericName: "FENITOÍNA SÓDICA", category: "psychotropic", presentation: "Ampola 5ml", unit: "amp", controlled: false },
  { name: "FENOBARBITAL 100MG", genericName: "FENOBARBITAL", category: "psychotropic", presentation: "Comprimido 100mg", unit: "cp", controlled: true },
  { name: "HALOPERIDOL 5MG", genericName: "HALOPERIDOL", category: "psychotropic", presentation: "Comprimido 5mg", unit: "cp", controlled: false },
  { name: "HALOPERIDOL 5MG/ML", genericName: "HALOPERIDOL", category: "psychotropic", presentation: "Ampola 1ml", unit: "amp", controlled: false },
  { name: "CLONAZEPAM 2MG", genericName: "CLONAZEPAM", category: "psychotropic", presentation: "Comprimido 2mg", unit: "cp", controlled: true },
  { name: "CLONAZEPAM 2,5MG/ML GOTAS", genericName: "CLONAZEPAM", category: "psychotropic", presentation: "Frasco 20ml", unit: "fr", controlled: true },
  { name: "ALPRAZOLAM 0,5MG", genericName: "ALPRAZOLAM", category: "psychotropic", presentation: "Comprimido 0,5mg", unit: "cp", controlled: true },
  { name: "ALPRAZOLAM 1MG", genericName: "ALPRAZOLAM", category: "psychotropic", presentation: "Comprimido 1mg", unit: "cp", controlled: true },
  { name: "LORAZEPAM 2MG", genericName: "LORAZEPAM", category: "psychotropic", presentation: "Comprimido 2mg", unit: "cp", controlled: true },
  { name: "BROMAZEPAM 3MG", genericName: "BROMAZEPAM", category: "psychotropic", presentation: "Comprimido 3mg", unit: "cp", controlled: true },
  { name: "AMITRIPTILINA 25MG", genericName: "CLORIDRATO DE AMITRIPTILINA", category: "psychotropic", presentation: "Comprimido 25mg", unit: "cp", controlled: true },
  { name: "FLUOXETINA 20MG", genericName: "CLORIDRATO DE FLUOXETINA", category: "psychotropic", presentation: "Cápsula 20mg", unit: "cap", controlled: true },
  { name: "FENOBARBITAL 40MG/ML GOTAS", genericName: "FENOBARBITAL", category: "psychotropic", presentation: "Frasco 20ml", unit: "fr", controlled: true },
  { name: "VALPROATO DE SÓDIO 250MG/5ML", genericName: "VALPROATO DE SÓDIO", category: "psychotropic", presentation: "Xarope 100ml", unit: "fr", controlled: true },
  { name: "CLORIDRATO DE SERTRALINA 50MG", genericName: "SERTRALINA", category: "psychotropic", presentation: "Comprimido 50mg", unit: "cp", controlled: true },
  { name: "PAROXETINA 20MG", genericName: "CLORIDRATO DE PAROXETINA", category: "psychotropic", presentation: "Comprimido 20mg", unit: "cp", controlled: true },
  { name: "CITALOPRAM 20MG", genericName: "BROMIDRATO DE CITALOPRAM", category: "psychotropic", presentation: "Comprimido 20mg", unit: "cp", controlled: true },
  { name: "ESCITALOPRAM 10MG", genericName: "OXALATO DE ESCITALOPRAM", category: "psychotropic", presentation: "Comprimido 10mg", unit: "cp", controlled: true },
  { name: "RISPERIDONA 1MG", genericName: "RISPERIDONA", category: "psychotropic", presentation: "Comprimido 1mg", unit: "cp", controlled: true },
  { name: "RISPERIDONA 2MG", genericName: "RISPERIDONA", category: "psychotropic", presentation: "Comprimido 2mg", unit: "cp", controlled: true },
  { name: "QUETIAPINA 25MG", genericName: "HEMIFUMARATO DE QUETIAPINA", category: "psychotropic", presentation: "Comprimido 25mg", unit: "cp", controlled: true },
  { name: "OLANZAPINA 5MG", genericName: "OLANZAPINA", category: "psychotropic", presentation: "Comprimido 5mg", unit: "cp", controlled: true },
  { name: "LÍTIO 300MG", genericName: "CARBONATO DE LÍTIO", category: "psychotropic", presentation: "Comprimido 300mg", unit: "cp", controlled: true },

  // Obstétricos
  { name: "OCITOCINA 5UI/ML", genericName: "OCITOCINA", category: "obstetric", presentation: "Ampola 1ml", unit: "amp", controlled: false },
  { name: "MISOPROSTOL 200MCG", genericName: "MISOPROSTOL", category: "obstetric", presentation: "Comprimido Vaginal", unit: "cp", controlled: true },

  // Soluções e Fluidos
  { name: "SORO FISIOLÓGICO 0,9% 500ML", genericName: "CLORETO DE SÓDIO 0,9%", category: "solution", presentation: "Bolsa/Frasco 500ml", unit: "fr", controlled: false },
  { name: "SORO FISIOLÓGICO 0,9% 250ML", genericName: "CLORETO DE SÓDIO 0,9%", category: "solution", presentation: "Bolsa/Frasco 250ml", unit: "fr", controlled: false },
  { name: "SORO FISIOLÓGICO 0,9% 100ML", genericName: "CLORETO DE SÓDIO 0,9%", category: "solution", presentation: "Bolsa/Frasco 100ml", unit: "fr", controlled: false },
  { name: "RINGER LACTATO 500ML", genericName: "RINGER LACTATO", category: "solution", presentation: "Bolsa/Frasco 500ml", unit: "fr", controlled: false },
  { name: "SORO GLICOSADO 5% 500ML", genericName: "GLICOSE 5%", category: "solution", presentation: "Bolsa/Frasco 500ml", unit: "fr", controlled: false },
  { name: "GLICOSE 50% 10ML", genericName: "GLICOSE 50%", category: "solution", presentation: "Ampola 10ml", unit: "amp", controlled: false },
  { name: "ÁGUA DESTILADA 10ML", genericName: "ÁGUA PARA INJETÁVEIS", category: "solution", presentation: "Ampola 10ml", unit: "amp", controlled: false },
  { name: "CLORETO DE SÓDIO 20% 10ML", genericName: "CLORETO DE SÓDIO 20%", category: "high-alert", presentation: "Ampola 10ml", unit: "amp", controlled: false },
  { name: "CLORETO DE POTÁSSIO 10% 10ML", genericName: "CLORETO DE POTÁSSIO 10%", category: "high-alert", presentation: "Ampola 10ml", unit: "amp", controlled: false },

  { name: "LIDOCAÍNA GEL 2% 30G", genericName: "CLORIDRATO DE LIDOCAÍNA", category: "supply", presentation: "Bisnaga 30g", unit: "tb", controlled: false },
  { name: "LIDOCAÍNA 2% C/ VASO (INJ)", genericName: "CLORIDRATO DE LIDOCAÍNA + EPINEFRINA", category: "emergency", presentation: "Frasco 20ml", unit: "fr", controlled: false },
  { name: "XILOCAÍNA SPRAY 10%", genericName: "LIDOCAÍNA", category: "supply", presentation: "Frasco 50ml", unit: "fr", controlled: false },

  // Pediatria / Gotas / Suspensões
  { name: "DIPIRONA GOTAS 500MG/ML", genericName: "DIPIRONA SÓDICA", category: "pediatric", presentation: "Frasco 20ml", unit: "fr", controlled: false },
  { name: "PARACETAMOL GOTAS 200MG/ML", genericName: "PARACETAMOL", category: "pediatric", presentation: "Frasco 15ml", unit: "fr", controlled: false },
  { name: "IBUPROFENO GOTAS 50MG/ML", genericName: "IBUPROFENO", category: "pediatric", presentation: "Frasco 30ml", unit: "fr", controlled: false },
  { name: "PREDNISOLONA 3MG/ML SOL", genericName: "FOSFATO SÓDICO DE PREDNISOLONA", category: "pediatric", presentation: "Frasco 60ml", unit: "fr", controlled: false },
  { name: "AMOXICILINA 250MG/5ML SUSP", genericName: "AMOXICILINA", category: "pediatric", presentation: "Frasco 150ml", unit: "fr", controlled: false },
  { name: "SAIS DE REIDRATAÇÃO ORAL", genericName: "CLORETO DE SÓDIO + POTÁSSIO + CITRATO + GLICOSE", category: "pediatric", presentation: "Envelope", unit: "env", controlled: false },

  // Insumos e Materiais
  { name: "SERINGA 1ML C/ AGULHA", genericName: "SERINGA DESCARTÁVEL", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "SERINGA 3ML C/ AGULHA", genericName: "SERINGA DESCARTÁVEL", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "SERINGA 5ML C/ AGULHA", genericName: "SERINGA DESCARTÁVEL", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "SERINGA 10ML C/ AGULHA", genericName: "SERINGA DESCARTÁVEL", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "SERINGA 20ML C/ AGULHA", genericName: "SERINGA DESCARTÁVEL", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "CATETER JELCO 20G", genericName: "CATETER VENOSO PERIFÉRICO", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "CATETER JELCO 22G", genericName: "CATETER VENOSO PERIFÉRICO", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "CATETER JELCO 24G", genericName: "CATETER VENOSO PERIFÉRICO", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "GAZE ESTÉRIL 7,5X7,5", genericName: "GAZE ESTÉRIL", category: "supply", presentation: "Pacote c/ 10", unit: "pct", controlled: false },
  { name: "EQUIPO MACROGOTAS", genericName: "EQUIPO PARA SORO", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "EQUIPO MICROGOTAS", genericName: "EQUIPO PARA SORO", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "LUVA DE PROCEDIMENTO M", genericName: "LUVA DE LÁTEX", category: "supply", presentation: "Caixa c/ 100", unit: "cx", controlled: false },
  { name: "LUVA DE PROCEDIMENTO P", genericName: "LUVA DE LÁTEX", category: "supply", presentation: "Caixa c/ 100", unit: "cx", controlled: false },
  { name: "MÁSCARA CIRÚRGICA", genericName: "MÁSCARA DESCARTÁVEL", category: "supply", presentation: "Caixa c/ 50", unit: "cx", controlled: false },
  { name: "SONDA NASOGASTRICA Nº 14", genericName: "SONDA NASOGASTRICA", category: "enteral", presentation: "Unidade", unit: "un", controlled: false },
  
  // Pediatria Adicional
  { name: "SIMETICONA GOTAS 75MG/ML", genericName: "SIMETICONA", category: "pediatric", presentation: "Frasco 15ml", unit: "fr", controlled: false },
  { name: "METOCLOPRAMIDA GOTAS 4MG/ML", genericName: "CLORIDRATO DE METOCLOPRAMIDA", category: "pediatric", presentation: "Frasco 10ml", unit: "fr", controlled: false },
  { name: "BROMOPRIDA GOTAS 4MG/ML", genericName: "BROMOPRIDA", category: "pediatric", presentation: "Frasco 20ml", unit: "fr", controlled: false },
  { name: "ESTOLATO DE ERITROMICINA 125MG/5ML", genericName: "ESTOLATO DE ERITROMICINA", category: "pediatric", presentation: "Suspensão 100ml", unit: "fr", controlled: false },
  { name: "CEFALEXINA 250MG/5ML SUSP", genericName: "CEFALEXINA", category: "pediatric", presentation: "Frasco 100ml", unit: "fr", controlled: false },
  { name: "DESLORATADINA 0,5MG/ML XPE", genericName: "DESLORATADINA", category: "pediatric", presentation: "Frasco 60ml", unit: "fr", controlled: false },
  { name: "AZITROMICINA 200MG/5ML SUSP", genericName: "AZITROMICINA", category: "pediatric", presentation: "Frasco 15ml", unit: "fr", controlled: false },
  { name: "SULFATO FERROSO GOTAS 25MG/ML", genericName: "SULFATO FERROSO", category: "pediatric", presentation: "Frasco 30ml", unit: "fr", controlled: false },
  { name: "VITAMINA D3 GOTAS 200UI/GOTA", genericName: "COLECALCIFEROL", category: "pediatric", presentation: "Frasco 10ml", unit: "fr", controlled: false },

  // Saneantes e Soluções Adicionais
  { name: "ÁLCOOL 70% 1000ML", genericName: "ÁLCOOL ETÍLICO 70%", category: "supply", presentation: "Frasco 1L", unit: "fr", controlled: false },
  { name: "CLOREXIDINA DEGERMANTE 2%", genericName: "DIGLICONATO DE CLOREXIDINA", category: "supply", presentation: "Frasco 1L", unit: "fr", controlled: false },
  { name: "CLOREXIDINA ALCOÓLICA 0,5%", genericName: "DIGLICONATO DE CLOREXIDINA", category: "supply", presentation: "Frasco 1L", unit: "fr", controlled: false },
  { name: "PVPI TÓPICO 10%", genericName: "POVIDONA-IODO", category: "supply", presentation: "Frasco 1L", unit: "fr", controlled: false },
  
  // Diagnóstico e Outros
  { name: "TIRA P/ GLICEMIA (ACCU-CHEK)", genericName: "TIRA REAGENTE", category: "supply", presentation: "Frasco c/ 50", unit: "fr", controlled: false },
  { name: "LANCETA P/ GLICEMIA", genericName: "LANCETA DESCARTÁVEL", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "SONDA VESICAL DE ALÍVIO Nº 12", genericName: "SONDA URETRAL", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "SONDA VESICAL DE DEMORA Nº 14", genericName: "SONDA FOLEY 2 VIAS", category: "supply", presentation: "Unidade", unit: "un", controlled: false },
  { name: "COLETOR DE URINA SIST. FECHADO", genericName: "BOLSA COLETORA", category: "supply", presentation: "Unidade", unit: "un", controlled: false }
];
