export const importedEmployees = [
  {
    id: "emp-diurno_a-1",
    name: "Renata Ap. Bueno Pereira",
    role: "RES.TECNICA",
    coren: "484843",
    shift_type: "rt_lideranca",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-2",
    name: "Alessandra de Paula O. da Silva",
    role: "ENFERMEIRA",
    coren: "799277",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-3",
    name: "Aline  Mendanha Cruz Rocha",
    role: "ENFERMEIRA",
    coren: "724970",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-4",
    name: "Bruna Soares dos Santos",
    role: "ENFERMEIRA",
    coren: "825872",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-5",
    name: "Luciel  Pereira Teles",
    role: "ENFERMEIRO",
    coren: "455944",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-6",
    name: "Maria Fernanda Oliveria Santana",
    role: "ENFERMEIRA",
    coren: "846551",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-7",
    name: "Rosangela da Silva Vasconcelos",
    role: "ENFERMEIRA",
    coren: "141534",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-8",
    name: "Tamires Bezerra Bomfim",
    role: "ENFERMEIRA",
    coren: "760670",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-9",
    name: "André Luiz Alves dos Santos",
    role: "TEC.ENF",
    coren: "2138328",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-10",
    name: "Antonia Mary Alves do Vale",
    role: "TEC.ENF",
    coren: "855302",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-11",
    name: "Doralice Alves  dos  Santos",
    role: "TEC.ENF",
    coren: "2139767",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-12",
    name: "Erica Almeida Salomão",
    role: "TEC.ENF",
    coren: "1947108",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-13",
    name: "Fabiana Aparecida dos Santos",
    role: "TEC.ENF",
    coren: "213777",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-14",
    name: "Lívia Maria Oliveira de França",
    role: "TEC.ENF",
    coren: "2146352",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-15",
    name: "Luiza Soares Pinheiro Coutinho",
    role: "TEC.ENF",
    coren: "1525834",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-16",
    name: "Maria Claudia Silva Santana",
    role: "TEC.ENF",
    coren: "866815",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-17",
    name: "Mariane Cardoso  Barbosa",
    role: "TEC.ENF",
    coren: "1927793",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-18",
    name: "Michele Ramos de Souza",
    role: "TEC.ENF",
    coren: "775483",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-19",
    name: "Rosangela Lopez de Araujo",
    role: "TEC.ENF",
    coren: "1639352",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-20",
    name: "Simone Alves dos Santos",
    role: "TEC.ENF",
    coren: "2429566",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-21",
    name: "Simone Pereira da Silva Sá",
    role: "TEC.ENF",
    coren: "1155549",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-22",
    name: "Tatiana da Silva Moteiro",
    role: "TEC.ENF",
    coren: "1458590",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-23",
    name: "Valmira Ramos Santana",
    role: "TEC.ENF",
    coren: "1532210",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_a-24",
    name: "Vanessa do Santos de Jesus",
    role: "TEC.ENF",
    coren: "2098995",
    shift_type: "diurno_a",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-26",
    name: "Adelia  Jaqueline Oliviera Gil",
    role: "ENFERMEIRA",
    coren: "298043",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-27",
    name: "Ana Beatriz Simão",
    role: "ENFERMEIRA",
    coren: "983755",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-28",
    name: "Daisy Silva de Paiva",
    role: "ENFERMEIRA",
    coren: "805294",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-29",
    name: "Darlene Dourado Santiago",
    role: "ENFERMEIRO",
    coren: "853159",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-30",
    name: "Ivonei da Silva Passos",
    role: "ENFERMEIRA",
    coren: "975413",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-31",
    name: "Janaina Batista dos Anjos Souza",
    role: "ENFERMEIRA",
    coren: "651599",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-32",
    name: "Marcela  Santos Silva Libarino",
    role: "ENFERMEIRA",
    coren: "809518",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-33",
    name: "Maria Eduarda Spadini de Oliviera",
    role: "LIDERANÇA",
    coren: "820597",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-34",
    name: "Marilene Pereira Dias Alves",
    role: "ENFERMEIRA",
    coren: "487780",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-35",
    name: "Roseli  M. de Olivera da Fonseca Santos",
    role: "ENFERMEIRA",
    coren: "851853",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-36",
    name: "Zileide Ribeiro de Malta",
    role: "ENFERMEIRA",
    coren: "836081",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-37",
    name: "Adriano  Soares de Araujo",
    role: "TEC.ENF",
    coren: "2156363",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-38",
    name: "Ana Carolina Souza da Paz",
    role: "TEC.ENF",
    coren: "2418466",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-39",
    name: "Andreza De Souza Gonçalves",
    role: "TEC.ENF",
    coren: "2418866",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-41",
    name: "Beatriz Fontes Teodoro",
    role: "TEC.ENF",
    coren: "2092522",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-42",
    name: "Edna Santos Aguiar",
    role: "TEC.ENF",
    coren: "1675649",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-43",
    name: "Eliane Sales da Silva",
    role: "TEC.ENF",
    coren: "2148891",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-44",
    name: "Goretti Fernanda Correia Bispo",
    role: "TEC.ENF",
    coren: "1045222",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-45",
    name: "Gustavo Santana",
    role: "TEC.ENF",
    coren: "1837781",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-46",
    name: "Luciana Batista da Silva",
    role: "TEC.ENF",
    coren: "2149268",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-47",
    name: "Paula Araujo de Souza",
    role: "TEC.ENF",
    coren: "14299302",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-48",
    name: "Sonia Pacheco",
    role: "TEC.ENF",
    coren: "884972",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-49",
    name: "Tamiris Pires Xavier",
    role: "TEC.ENF",
    coren: "1199714",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-diurno_b-50",
    name: "Tatiana Rose da Conceição",
    role: "TEC.ENF",
    coren: "262811",
    shift_type: "diurno_b",
    work_hours: "07:00 as 19:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-52",
    name: "Bruna Silva Oliveira",
    role: "ENFERMEIRA",
    coren: "724970",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-53",
    name: "Caroline Virginia de Oliveira",
    role: "ENFERMEIRO",
    coren: "860622",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-54",
    name: "Cilene Mendes Fernandes",
    role: "ENFERMEIRA",
    coren: "202263",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-55",
    name: "Gabrielly Lima Reis",
    role: "ENFERMEIRA",
    coren: "820763",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-56",
    name: "Gislaine Luiza Teles Almeida",
    role: "ENFERMEIRA",
    coren: "825682",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-57",
    name: "Sandra de F.Santos Chaves",
    role: "ENFERMEIRA",
    coren: "641066",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-58",
    name: "Ana Maria Ribeiro Gomes",
    role: "TEC.ENF",
    coren: "486495",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-59",
    name: "Cintia Maria  da Silva",
    role: "TEC.ENF",
    coren: "59138",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-61",
    name: "Elitania Silva Santos",
    role: "TEC.ENF",
    coren: "1691058",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-62",
    name: "Felipe G. do Nascimento Cruz",
    role: "TEC.ENF",
    coren: "331057",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-63",
    name: "Kesia Sueli de Sousa",
    role: "TEC.ENF",
    coren: "781391",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-64",
    name: "Maria  Aparecida Conceição",
    role: "TEC.ENF",
    coren: "493663",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-65",
    name: "Maria Rita da Silva Sena",
    role: "TEC.ENF",
    coren: "849455",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-66",
    name: "Marilene Ribeiro Moreno de Souza",
    role: "TEC.ENF",
    coren: "537659",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-67",
    name: "Midia Camargo da Silva",
    role: "TEC.ENF",
    coren: "1390366",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-68",
    name: "Veronica de Souza Moreira",
    role: "TEC.ENF",
    coren: "2415278",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-69",
    name: "Andréia Maria Annanias",
    role: "AUX.ENF",
    coren: "326836",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-70",
    name: "Francisco José Gomes",
    role: "AUX.ENF",
    coren: "392616",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-71",
    name: "Miriam de Aquino Costa",
    role: "AUX.ENF",
    coren: "1048151",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_a-72",
    name: "Quiteria Nunes de Almeida",
    role: "AUX.ENF",
    coren: "130298",
    shift_type: "noturno_a",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-74",
    name: "Helio de Melo Nunes Junior",
    role: "ENFERMEIRO",
    coren: "615864",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-75",
    name: "Jailton Silva de Oliveira",
    role: "ENFERMEIRO",
    coren: "551577",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-76",
    name: "Karina Targino Silva",
    role: "ENFERMEIRA",
    coren: "704914",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-77",
    name: "Stephanie de Lima Alves",
    role: "ENFERMEIRO",
    coren: "836772",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-78",
    name: "Thaina Santana  Silva",
    role: "ENFERMEIRO",
    coren: "615864",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-79",
    name: "Ana Claudia de Oliveira Melo",
    role: "TEC.ENF",
    coren: "1951727",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-80",
    name: "Aparecida de Oliviera Gama",
    role: "TEC.ENF",
    coren: "1389159",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-81",
    name: "Estefanie Rodrigues da Silva",
    role: "TEC.ENF",
    coren: "1652216",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-82",
    name: "Jaqueline   Pereira Bonifacio",
    role: "TEC.ENF",
    coren: "1830367",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-83",
    name: "Jussara Souza Lira",
    role: "TEC.ENF",
    coren: "1342555",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-84",
    name: "Luana Barboza Vitoriano",
    role: "TEC.ENF",
    coren: "1162512",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-85",
    name: "Maria da Silva Balboa",
    role: "TEC.ENF",
    coren: "1162053",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-86",
    name: "Maria das Graças da Silva Linhares",
    role: "TEC.ENF",
    coren: "1723584",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-87",
    name: "Maria José F. A. de Menezes",
    role: "TEC.ENF",
    coren: "3455",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-88",
    name: "Pamela Marinho dos Santos",
    role: "TEC.ENF",
    coren: "1063810",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-89",
    name: "Prisicila Neves Carvalho",
    role: "TEC.ENF",
    coren: "2036705",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-90",
    name: "Taiane Souza Lima",
    role: "TEC.ENF",
    coren: "1683071",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-91",
    name: "Tamires do Nascimento Cardoso",
    role: "TEC.ENF",
    coren: "1647323",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "impar",
    contract_type: "CLT",
    status: "active",
  },
  {
    id: "emp-noturno_b-92",
    name: "Veluzia  Dias Matos  Libarino",
    role: "TEC.ENF",
    coren: "1736681",
    shift_type: "noturno_b",
    work_hours: "19:00 as 07:00",
    sector: "Geral",
    cycle: "par",
    contract_type: "CLT",
    status: "active",
  },
];

export const importedSchedules = [
  {
    id: "sch-emp-diurno_a-1",
    employee_id: "emp-diurno_a-1",
    employee_name: "Renata Ap. Bueno Pereira",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "P",
      3: "P",
      4: "P",
      5: "P",
      6: "F",
      7: "F",
      8: "P",
      9: "P",
      10: "P",
      11: "P",
      12: "P",
      13: "F",
      14: "F",
      15: "P",
      16: "P",
      17: "P",
      18: "P",
      19: "P",
      20: "F",
      21: "F",
      22: "P",
      23: "P",
      24: "P",
      25: "P",
      26: "P",
      27: "F",
      28: "F",
      29: "P",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-2",
    employee_id: "emp-diurno_a-2",
    employee_name: "Alessandra de Paula O. da Silva",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "LM",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-3",
    employee_id: "emp-diurno_a-3",
    employee_name: "Aline  Mendanha Cruz Rocha",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-4",
    employee_id: "emp-diurno_a-4",
    employee_name: "Bruna Soares dos Santos",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-5",
    employee_id: "emp-diurno_a-5",
    employee_name: "Luciel  Pereira Teles",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-6",
    employee_id: "emp-diurno_a-6",
    employee_name: "Maria Fernanda Oliveria Santana",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-7",
    employee_id: "emp-diurno_a-7",
    employee_name: "Rosangela da Silva Vasconcelos",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-8",
    employee_id: "emp-diurno_a-8",
    employee_name: "Tamires Bezerra Bomfim",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-9",
    employee_id: "emp-diurno_a-9",
    employee_name: "André Luiz Alves dos Santos",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-10",
    employee_id: "emp-diurno_a-10",
    employee_name: "Antonia Mary Alves do Vale",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-11",
    employee_id: "emp-diurno_a-11",
    employee_name: "Doralice Alves  dos  Santos",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-12",
    employee_id: "emp-diurno_a-12",
    employee_name: "Erica Almeida Salomão",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-13",
    employee_id: "emp-diurno_a-13",
    employee_name: "Fabiana Aparecida dos Santos",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-14",
    employee_id: "emp-diurno_a-14",
    employee_name: "Lívia Maria Oliveira de França",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-15",
    employee_id: "emp-diurno_a-15",
    employee_name: "Luiza Soares Pinheiro Coutinho",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-16",
    employee_id: "emp-diurno_a-16",
    employee_name: "Maria Claudia Silva Santana",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-17",
    employee_id: "emp-diurno_a-17",
    employee_name: "Mariane Cardoso  Barbosa",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-18",
    employee_id: "emp-diurno_a-18",
    employee_name: "Michele Ramos de Souza",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-19",
    employee_id: "emp-diurno_a-19",
    employee_name: "Rosangela Lopez de Araujo",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-20",
    employee_id: "emp-diurno_a-20",
    employee_name: "Simone Alves dos Santos",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-21",
    employee_id: "emp-diurno_a-21",
    employee_name: "Simone Pereira da Silva Sá",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-22",
    employee_id: "emp-diurno_a-22",
    employee_name: "Tatiana da Silva Moteiro",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "LM",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-23",
    employee_id: "emp-diurno_a-23",
    employee_name: "Valmira Ramos Santana",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_a-24",
    employee_id: "emp-diurno_a-24",
    employee_name: "Vanessa do Santos de Jesus",
    month: 6,
    year: 2026,
    shift_type: "diurno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-26",
    employee_id: "emp-diurno_b-26",
    employee_name: "Adelia  Jaqueline Oliviera Gil",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-27",
    employee_id: "emp-diurno_b-27",
    employee_name: "Ana Beatriz Simão",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-28",
    employee_id: "emp-diurno_b-28",
    employee_name: "Daisy Silva de Paiva",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-29",
    employee_id: "emp-diurno_b-29",
    employee_name: "Darlene Dourado Santiago",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-30",
    employee_id: "emp-diurno_b-30",
    employee_name: "Ivonei da Silva Passos",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-31",
    employee_id: "emp-diurno_b-31",
    employee_name: "Janaina Batista dos Anjos Souza",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-32",
    employee_id: "emp-diurno_b-32",
    employee_name: "Marcela  Santos Silva Libarino",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-33",
    employee_id: "emp-diurno_b-33",
    employee_name: "Maria Eduarda Spadini de Oliviera",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "P",
      2: "P",
      3: "P",
      4: "P",
      5: "P",
      6: "F",
      7: "F",
      8: "P",
      9: "P",
      10: "P",
      11: "P",
      12: "P",
      13: "F",
      14: "F",
      15: "P",
      16: "P",
      17: "P",
      18: "P",
      19: "P",
      20: "F",
      21: "F",
      22: "P",
      23: "P",
      24: "P",
      25: "P",
      26: "P",
      27: "F",
      28: "F",
      29: "P",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-34",
    employee_id: "emp-diurno_b-34",
    employee_name: "Marilene Pereira Dias Alves",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "LM",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-35",
    employee_id: "emp-diurno_b-35",
    employee_name: "Roseli  M. de Olivera da Fonseca Santos",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-36",
    employee_id: "emp-diurno_b-36",
    employee_name: "Zileide Ribeiro de Malta",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-37",
    employee_id: "emp-diurno_b-37",
    employee_name: "Adriano  Soares de Araujo",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-38",
    employee_id: "emp-diurno_b-38",
    employee_name: "Ana Carolina Souza da Paz",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-39",
    employee_id: "emp-diurno_b-39",
    employee_name: "Andreza De Souza Gonçalves",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-41",
    employee_id: "emp-diurno_b-41",
    employee_name: "Beatriz Fontes Teodoro",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-42",
    employee_id: "emp-diurno_b-42",
    employee_name: "Edna Santos Aguiar",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-43",
    employee_id: "emp-diurno_b-43",
    employee_name: "Eliane Sales da Silva",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-44",
    employee_id: "emp-diurno_b-44",
    employee_name: "Goretti Fernanda Correia Bispo",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-45",
    employee_id: "emp-diurno_b-45",
    employee_name: "Gustavo Santana",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-46",
    employee_id: "emp-diurno_b-46",
    employee_name: "Luciana Batista da Silva",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-47",
    employee_id: "emp-diurno_b-47",
    employee_name: "Paula Araujo de Souza",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-48",
    employee_id: "emp-diurno_b-48",
    employee_name: "Sonia Pacheco",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-49",
    employee_id: "emp-diurno_b-49",
    employee_name: "Tamiris Pires Xavier",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-diurno_b-50",
    employee_id: "emp-diurno_b-50",
    employee_name: "Tatiana Rose da Conceição",
    month: 6,
    year: 2026,
    shift_type: "diurno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-52",
    employee_id: "emp-noturno_a-52",
    employee_name: "Bruna Silva Oliveira",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-53",
    employee_id: "emp-noturno_a-53",
    employee_name: "Caroline Virginia de Oliveira",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-54",
    employee_id: "emp-noturno_a-54",
    employee_name: "Cilene Mendes Fernandes",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-55",
    employee_id: "emp-noturno_a-55",
    employee_name: "Gabrielly Lima Reis",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-56",
    employee_id: "emp-noturno_a-56",
    employee_name: "Gislaine Luiza Teles Almeida",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-57",
    employee_id: "emp-noturno_a-57",
    employee_name: "Sandra de F.Santos Chaves",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-58",
    employee_id: "emp-noturno_a-58",
    employee_name: "Ana Maria Ribeiro Gomes",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-59",
    employee_id: "emp-noturno_a-59",
    employee_name: "Cintia Maria  da Silva",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-61",
    employee_id: "emp-noturno_a-61",
    employee_name: "Elitania Silva Santos",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-62",
    employee_id: "emp-noturno_a-62",
    employee_name: "Felipe G. do Nascimento Cruz",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-63",
    employee_id: "emp-noturno_a-63",
    employee_name: "Kesia Sueli de Sousa",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-64",
    employee_id: "emp-noturno_a-64",
    employee_name: "Maria  Aparecida Conceição",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-65",
    employee_id: "emp-noturno_a-65",
    employee_name: "Maria Rita da Silva Sena",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-66",
    employee_id: "emp-noturno_a-66",
    employee_name: "Marilene Ribeiro Moreno de Souza",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-67",
    employee_id: "emp-noturno_a-67",
    employee_name: "Midia Camargo da Silva",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-68",
    employee_id: "emp-noturno_a-68",
    employee_name: "Veronica de Souza Moreira",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-69",
    employee_id: "emp-noturno_a-69",
    employee_name: "Andréia Maria Annanias",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-70",
    employee_id: "emp-noturno_a-70",
    employee_name: "Francisco José Gomes",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-71",
    employee_id: "emp-noturno_a-71",
    employee_name: "Miriam de Aquino Costa",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "V",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_a-72",
    employee_id: "emp-noturno_a-72",
    employee_name: "Quiteria Nunes de Almeida",
    month: 6,
    year: 2026,
    shift_type: "noturno_a",
    days: {
      1: "P",
      2: "F",
      3: "P",
      4: "F",
      5: "P",
      6: "F",
      7: "P",
      8: "F",
      9: "P",
      10: "F",
      11: "P",
      12: "F",
      13: "P",
      14: "F",
      15: "P",
      16: "F",
      17: "P",
      18: "F",
      19: "P",
      20: "F",
      21: "P",
      22: "F",
      23: "P",
      24: "F",
      25: "P",
      26: "F",
      27: "P",
      28: "F",
      29: "P",
      30: "F",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-74",
    employee_id: "emp-noturno_b-74",
    employee_name: "Helio de Melo Nunes Junior",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-75",
    employee_id: "emp-noturno_b-75",
    employee_name: "Jailton Silva de Oliveira",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-76",
    employee_id: "emp-noturno_b-76",
    employee_name: "Karina Targino Silva",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-77",
    employee_id: "emp-noturno_b-77",
    employee_name: "Stephanie de Lima Alves",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-78",
    employee_id: "emp-noturno_b-78",
    employee_name: "Thaina Santana  Silva",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-79",
    employee_id: "emp-noturno_b-79",
    employee_name: "Ana Claudia de Oliveira Melo",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-80",
    employee_id: "emp-noturno_b-80",
    employee_name: "Aparecida de Oliviera Gama",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-81",
    employee_id: "emp-noturno_b-81",
    employee_name: "Estefanie Rodrigues da Silva",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-82",
    employee_id: "emp-noturno_b-82",
    employee_name: "Jaqueline   Pereira Bonifacio",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-83",
    employee_id: "emp-noturno_b-83",
    employee_name: "Jussara Souza Lira",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-84",
    employee_id: "emp-noturno_b-84",
    employee_name: "Luana Barboza Vitoriano",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-85",
    employee_id: "emp-noturno_b-85",
    employee_name: "Maria da Silva Balboa",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-86",
    employee_id: "emp-noturno_b-86",
    employee_name: "Maria das Graças da Silva Linhares",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-87",
    employee_id: "emp-noturno_b-87",
    employee_name: "Maria José F. A. de Menezes",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-88",
    employee_id: "emp-noturno_b-88",
    employee_name: "Pamela Marinho dos Santos",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-89",
    employee_id: "emp-noturno_b-89",
    employee_name: "Prisicila Neves Carvalho",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-90",
    employee_id: "emp-noturno_b-90",
    employee_name: "Taiane Souza Lima",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-91",
    employee_id: "emp-noturno_b-91",
    employee_name: "Tamires do Nascimento Cardoso",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
  {
    id: "sch-emp-noturno_b-92",
    employee_id: "emp-noturno_b-92",
    employee_name: "Veluzia  Dias Matos  Libarino",
    month: 6,
    year: 2026,
    shift_type: "noturno_b",
    days: {
      1: "F",
      2: "P",
      3: "F",
      4: "P",
      5: "F",
      6: "P",
      7: "F",
      8: "P",
      9: "F",
      10: "P",
      11: "F",
      12: "P",
      13: "F",
      14: "P",
      15: "F",
      16: "P",
      17: "F",
      18: "P",
      19: "F",
      20: "P",
      21: "F",
      22: "P",
      23: "F",
      24: "P",
      25: "F",
      26: "P",
      27: "F",
      28: "P",
      29: "F",
      30: "P",
    },
    locked: false,
  },
];
